# Generated by Django 5.0.7 on 2026-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fonction_user_prefecture_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('cadastre', 'Agent du cadastre'), ('tribunal', 'Agent du tribunal'), ('consultation', 'Consultation')], default='consultation', max_length=30),
        ),
    ]
