# Generated by Django 5.0.7 on 2026-09-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_prefecture_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fonction',
        ),
    ]
