# Generated by Django 5.0.7 on 2026-09-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField()),
                ('type_plainte', models.CharField(max_length=80)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitée'), ('rejetee', 'Rejetée')], default='en_cours', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintes', to='parcelles.parcelle')),
            ],
            options={
                'db_table': 'plaintes',
            },
        ),
    ]
