# Generated by Django 5.0.7 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaintes', '0003_remove_plainte_document_parcelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='reponse_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plainte',
            name='reponse_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
