services:
  - type: web
    name: landguard-alert
    runtime: python
    plan: free
    buildCommand: "pip install -r src/requirements.txt && python src/manage.py collectstatic --noinput"
    startCommand: "gunicorn --chdir src landguard_python.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.6"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "landguard-alert.onrender.com,localhost,127.0.0.1"
      - key: DB_NAME
        value: "landguard"
      - key: DB_USER
        value: "postgres"
      - key: DB_PASSWORD
        value: "postgres"
      - key: DB_HOST
        value: "localhost"
      - key: DB_PORT
        value: "5432"

databases:
  - name: landguard-db
    databaseName: landguard
    user: landguard
    plan: free
