# Generated by Django 5.0.7 on 2026-09-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80, unique=True)),
                ('commune', models.CharField(max_length=120)),
                ('prefecture', models.CharField(max_length=120)),
                ('superficie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('geom', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcelles',
            },
        ),
    ]
