# Generated by Django 5.0.7 on 2026-09-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('litiges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80, unique=True)),
                ('tribunal', models.CharField(max_length=120)),
                ('resume', models.TextField()),
                ('statut', models.CharField(default='en_attente', max_length=50)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('date_transmission', models.DateTimeField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_crees', to=settings.AUTH_USER_MODEL)),
                ('litige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='litiges.litige')),
            ],
            options={
                'db_table': 'decisions',
            },
        ),
    ]
