# Generated by Django 5.0.7 on 2026-09-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0001_initial'),
        ('plaintes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80, unique=True)),
                ('objet', models.CharField(max_length=200)),
                ('parties', models.TextField(blank=True, null=True)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='ouvert', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_crees', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='parcelles.parcelle')),
                ('plainte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges', to='plaintes.plainte')),
            ],
            options={
                'db_table': 'litiges',
            },
        ),
    ]
