# Generated by Django 5.0.7 on 2026-09-22 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litiges', '0002_litige_admin_response_litige_admin_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litige',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='litige',
            name='admin_validated_at',
        ),
        migrations.RemoveField(
            model_name='litige',
            name='cadastre_notes',
        ),
        migrations.RemoveField(
            model_name='litige',
            name='position_confirmee',
        ),
        migrations.AddField(
            model_name='litige',
            name='commentaire_validation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='parcelle_bloquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='litige',
            name='position_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='position_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='traite_par_cadastre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_cadastre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litige',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litige',
            name='valide_par_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='litige',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours_cadastre', 'En cours au cadastre'), ('bloque', 'Parcelle bloquée'), ('en_attente_validation', 'En attente de validation'), ('valide', 'Validé'), ('resolu', 'Résolu')], default='ouvert', max_length=50),
        ),
    ]
