# Generated by Django 5.0.7 on 2026-09-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
        ('plaintes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='demandeur_adresse',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='plainte',
            name='demandeur_contact',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='plainte',
            name='demandeur_nom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plainte',
            name='demandeur_prenom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plainte',
            name='document_parcelle',
            field=models.FileField(blank=True, null=True, upload_to='dossiers/parcelles/'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='opposant_adresse',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='plainte',
            name='opposant_contact',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='plainte',
            name='opposant_nom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plainte',
            name='opposant_prenom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plainte',
            name='reponse_cadastre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plainte',
            name='transmis_cadastre_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='parcelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes', to='parcelles.parcelle'),
        ),
    ]
