# Generated by Django 5.0.7 on 2026-09-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
        ('plaintes', '0002_plainte_demandeur_adresse_plainte_demandeur_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plainte',
            name='document_parcelle',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='reponse_cadastre',
        ),
        migrations.RemoveField(
            model_name='plainte',
            name='transmis_cadastre_at',
        ),
        migrations.AddField(
            model_name='plainte',
            name='plan_parcellaire',
            field=models.FileField(blank=True, null=True, upload_to='pieces/plans/'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='titre_foncier',
            field=models.FileField(blank=True, null=True, upload_to='pieces/titres/'),
        ),
        migrations.AddField(
            model_name='plainte',
            name='type_litige',
            field=models.CharField(default='Autre', max_length=120),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='demandeur_adresse',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='demandeur_contact',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='demandeur_nom',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='demandeur_prenom',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='opposant_adresse',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='opposant_contact',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='opposant_nom',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='opposant_prenom',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintes', to='parcelles.parcelle'),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitée'), ('rejetee', 'Rejetée'), ('transmise_cadastre', 'Transmise au cadastre')], default='en_cours', max_length=30),
        ),
    ]
