# Generated by Django 5.0.7 on 2026-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='prefecture',
            field=models.CharField(choices=[('Golfe', 'Golfe'), ('Agoè-Nyivé', 'Agoè-Nyivé'), ('Bas-Mono', 'Bas-Mono'), ('Lacs', 'Lacs'), ('Vo', 'Vo'), ('Yoto', 'Yoto'), ('Avé', 'Avé'), ('Zio', 'Zio')], default='Golfe', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('cadastre', 'Agent du cadastre'), ('tribunal', 'Agent du tribunal'), ('consultation', 'Utilisateur en consultation')], default='consultation', max_length=30),
        ),
    ]
