# Generated by Django 5.0.7 on 2026-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litiges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litige',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='admin_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='cadastre_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='position_confirmee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='litige',
            name='statut',
            field=models.CharField(choices=[('a_positionner', 'À positionner par le cadastre'), ('en_attente_validation', 'En attente de validation'), ('valide', 'Validé'), ('resolu', 'Problème réglé')], default='a_positionner', max_length=50),
        ),
    ]
